kind = "mobile"
previewPath = "/"
title = "EV SmartCharge"
version = "1.0.0"
id = "artifacts/ev-smartcharge"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24055

[services.development]
run = "pnpm --filter @workspace/ev-smartcharge run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ev-smartcharge", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/ev-smartcharge", "run", "serve" ]

[services.env]
PORT = "24055"
BASE_PATH = "/"
